version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get update
      - apt-get install -y build-essential
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
